# Generated by Django 2.2 on 2019-07-03 14:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=150, verbose_name='标题')),
                ('image_url', models.URLField(default='', help_text='图片url', verbose_name='图片url')),
                ('content', tinymce.models.HTMLField()),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '实时快讯',
                'db_table': 'RT_news',
                'verbose_name_plural': '实时快讯',
                'ordering': ['-create_date', '-id'],
            },
        ),
    ]
