# Generated by Django 2.2 on 2019-07-04 09:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=150, verbose_name='标题')),
                ('image_url', models.ImageField(blank=True, default='', upload_to='img')),
                ('content', tinymce.models.HTMLField()),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'db_table': 'EP_comm',
                'ordering': ['-create_date', '-id'],
                'verbose_name_plural': '专家点评',
                'verbose_name': '专家点评',
            },
        ),
    ]
