# Generated by Django 2.2 on 2019-05-06 18:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190505_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
