# Generated by Django 2.2 on 2019-05-09 13:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190506_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goldinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(default='', max_length=50)),
                ('pub_time', models.DateTimeField()),
                ('new_type', models.CharField(max_length=10)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Newinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(default='', max_length=50)),
                ('pub_time', models.DateTimeField()),
                ('new_type', models.CharField(max_length=10)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='new_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
