# Generated by Django 2.2 on 2019-05-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190509_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goldinfo',
        ),
        migrations.DeleteModel(
            name='Newinfo',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='user',
        ),
    ]
