# Generated by Django 2.2 on 2019-06-27 08:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=150, verbose_name='标题')),
                ('tags', models.CharField(help_text='新闻类型', max_length=200, verbose_name='新闻类型')),
                ('content', tinymce.models.HTMLField()),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'ordering': ['-create_date', '-id'],
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'db_table': 'tb_news',
            },
        ),
    ]
